Librarys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
   path('', include('main.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    
    # path('',views.Index,name='home'),
    
    path('',views.HomePage.as_view(),name='homepage'),
    
    path('Books',views.all,name='all'),
    
    path('contact',views.contact,name='contact'),
   
    path('About',views.aboutpageview.as_view(),name='about'),

    path('list/',views.booklistview.as_view(),name='List_Book'),
    
    path('books/add',views.BookCreateView.as_view(),name='books_add'),
    
    path('dash/',views.BookListView.as_view(),name='dash'),
    
    path('books/',views.BookListView.as_view(),name='book_list'),
    
    path('category/',views.CategoryListView.as_view(),name='list_cate'),
    
    path('author/',views.AuthorListView.as_view(),name='list_auth'),
    
    
    path('books/edit/<int:pk>',views.BookUpdateView.as_view(),name='books_edit'),

    path('books/detail/<int:pk>',views.BookDetailView.as_view(),name='books_detail'),
    
    path('books/Delete/<int:pk>',views.BookDeleteView.as_view(),name='books_delete'),

    path('login/',views.login_view,name='login'),
    
    path('loginmember/<int:id>',views.login_member,name='loginmem'),

    path('member',views.login_memberf,name='pro_memb'),
    
    path('admin-site/',views.login_view,name='admin-site'),
   
    path('logout/',views.logout_view,name='logout'),

    path('Book/<int:id>',views.single_book,name='single_book'),

    path('dashboard',views.dashboard,name='dashboard'),

    path('pdf_page/<int:id>', views.pdf_page, name='pdf_page'),

    # path('add/',views.book_add,name='add_Book'),

    path('register/',views.Register,name='Register'),

    path('dash/user/add/',views.AddUser,name='adduser'),

    # path('categ_add',views.categ_add,name='add_categ'),

    # path('author_add',views.author_add,name='add_auth'),
    
    path('profile/<str:name>',views.profile_memb,name='profile'),

    path("Category/<str:cate>",views.Category_Books,name='one_category'),

    path('category/<str:cate>/', views.category_detail, name='category_detail'),


    path('dash/user', views.UserListView.as_view(), name='users'),
    path('dash/books', views.BookListView.as_view(), name='books'),
    path('dash/categories/', views.CategoryListView.as_view(), name='categories'),
    path('dash/authors/', views.AuthorListView.as_view(), name='authors'),

    path('dash/user/add/', views.AddUserViews.as_view(), name='add_user'),
    path('dash/books/add/', views.AddBookViews.as_view(), name='add_book'),
    path('dash/categories/add/', views.AddCategoryViews.as_view(), name='add_categories'),
    path('dash/authors/add/', views.AddAuthorViews.as_view(), name='add_author'),

    path('dash/user/<int:pk>/edit/', views.BookUpdateViews.as_view(), name='update_user'),
    path('dash/books/<int:pk>/edit/', views.BookUpdateViews.as_view(), name='update_book'),
    path('dash/categories/<int:pk>/edit/', views.CategoryUpdateViews.as_view(), name='update_category'),
    path('dash/authors/<int:pk>/edit/', views.AuthorUpdateViews.as_view(), name='update_author'),

    path('dash/user/<int:pk>/delete/', views.BookDeleteViews.as_view(), name='delete_user'),
    path('dash/books/<int:pk>/delete/', views.BookDeleteViews.as_view(), name='delete_book'),
    path('dash/categories/<int:pk>/delete/', views.CategoryDeleteViews.as_view(), name='delete_category'),
    path('dash/authors/<int:pk>/delete/', views.AuthorDeleteViews.as_view(), name='delete_author'),

    path('dash/user/<int:pk>/', views.BookDetailViews.as_view(), name='user_detail'),
    path('dash/books/<int:pk>/', views.BookDetailViews.as_view(), name='book_detail'),
    path('dash/categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('dash/authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),


]

main/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100)
    

    def __str__(self):
        return str(self.name)

class Author(models.Model):
    author=models.CharField(max_length=100)
    about=models.CharField(max_length=100)
  
    def __str__(self):
        return str(self.author)

class Book(models.Model):
    title=models.CharField(max_length=100)
    date_pub=models.DateField(null=True)
    publisher=models.CharField(max_length=20)
    # copies=models.CharField()
    description=models.TextField(null=True)
    image=models.ImageField(upload_to='photos')
    categ=models.ManyToManyField('Category', related_name='books')
    author=models.ForeignKey(Author,on_delete=models.CASCADE,related_name='books')
    page_num=models.IntegerField()
    file = models.FileField(upload_to='files',null=True)
   
    class  Mate:

        permissions = [
        ('can_publish', 'Can publish '),
        ('can_edit_published', 'Can edit published '),
    ]    
        
    def __str__(self):
        return str(self.title)

  
# class Bookcop(models.Model):
#     un_id=models.IntegerField(unique=True)
#     book_id=models.ForeignKey(Book,on_delete=models.CASCADE)
#     is_av=models.BooleanField(default=True)


#     def __str__(self):
#         return str(self.un_id)

class Member(models.Model):
    name=models.CharField(max_length=100)
    about=models.CharField(max_length=200)
    email=models.EmailField()
    password=models.CharField(max_length=10,null=True)
    image=models.ImageField(upload_to='photos/member', null=True)
    # user=models.OneToOneField('auth.User',on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return str(self.name)
    
class Borrowing(models.Model):
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    member_id=models.ForeignKey(Member,on_delete=models.CASCADE)
    borrow_date=models.DateTimeField(auto_now_add=True)
    return_date=models.DateTimeField(null=True,blank=True)
    activate_date=models.DateTimeField(null=True,blank=True)
    is_returned=models.BooleanField(default=False)
    Cost=models.DecimalField(max_digits=6,decimal_places=2,null=True,blank=True)

    def __str__(self):
        return str(self.book)
    

templates/dash/Base_all.html
{%load static%}
{% load custom_filter %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>DashBoard CBV</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'dashboard/img/lib.jpg'%}" rel="icon">
  <link href="{% static 'dashboard/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'dashboard/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'dashboard/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'dashboard/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'dashboard/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'dashboard/vendor/swiper/swiper-bundle.min.css'}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'dashboard/css/main.css'%}" rel="stylesheet">
</head>
<body class="index-page">

  
<div class="content">
    <div class="row">
    <div class="col-lg-3">
    <header id="header" class="header dark-background d-flex flex-column">
    <i class="header-toggle d-xl-none bi bi-list"></i>
    <h5 class="sitename pt-5">DashBoard</h5>

    <div class="profile-img">
      <img src="/static/dashboard/img/hero-bg.jpg" alt="" class="w-100">
    </div>

 

  
    {% block sidebar %}
    {% sidebar_tag model_name %}
    {% endblock %}

  </header>
    </div>
    <div class="col-lg-8 pt-5">
    {% block content %}{% endblock %}
    </div>
</div>
</div>
</body>
</html> 
 

templates/dash/Detailobj.html
{% extends "dash/Base_all.html" %} {% load custom_filter %} {% block content %}
<div class="container mt-4">
  <div class="col-md-10 col-lg-8">
    <div class="">
      <h2 class="mb-5">{{ model_name }} Details</h2>
    </div>

    <div class="card-body">
      <div class="row g-3">
        {% for field in fields_info %}
        <div class="col-12">
          <strong>{{ field.label|capfirst }}:</strong>
          {% if field.is_image and field.value %}
          <div class="mt-2 mb-3">
            <img
              src="{{ field.value.url }}"
              alt="{{ field.label }}"
              class="img-fluid rounded"
              style="max-height: 300px"
            />
          </div>
          {% else %} {% if field.is_many_to_many %}
          <p class="mb-3">{{ field.value.all|join:", " }}</p>
          {% else %}
          <p class="mb-3">{{ field.value }}</p>
          {% endif %} {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/dash/ListView.html
{% extends "dash/Base_all.html" %} {% load custom_filter %}

{% block content %}

<h5 style=" text-align: right;"> Welcome <strong style="color: green;">{{user.username}}</strong> 
<a href="{% url 'logout' %}"><i class="bi bi-box-arrow-right text-danger fs-3 navicon"></i> </a></li>
</h5>
 
 <h3 style="text-align: center;"> {{ model_name }} List </h3>

 <div class="row " style="width: 100% ;">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-body-tertiary rounded-3 p-4 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'dash'%}">Home</a></li>
            <li class="breadcrumb-item"><a href="#">{{ model_name }} </a></li>
          
          </ol>
        </nav>
      </div>
    </div>
    <p>Total : {% get_count   objects %}</p>
    
  
 {% if can_add %}   
<a
  href="{{ add_url }}"
  class="btn mb-3"
  style="background: #daa556; color: white; padding: 10px"
  >Add {{ model_name }} <i class="bi bi-plus" style="padding: 0 5px"></i
></a>
{%endif%}
<table class="table table-striped" >
  <thead>
    <tr>
      {% for header in headers %}
      <th>{{ header }}</th>
      {% endfor %}
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in objects %}
    <tr>
     {% for column in columns %}

  {% if column == 'image' %}
    <td>
      {% with img=obj|attr:column %}
        {% if img %}
          <a href="{% url detail_url obj.id %}">
            <img src="{{ img.url }}" style="width: 30px" />
          </a>
        {% endif %}
      {% endwith %}
    </td>

  {% elif column == 'categ' %}
    <td>
      {% view_many_to_many obj.categ.all %}
    </td>

  {% else %}
    <td>{{ obj|attr:column }}</td>
  {% endif %}

{% endfor %}

      <td>
        <!-- <a href="{{ obj.detail_url }}">View</a> -->
        {% if can_change %}
        <a href="{% url update_url obj.id %}"style ="border: 1px solid rgb(127, 248, 127) ;color:rgb(12, 139, 12) ; padding: 5px 22px;  border-radius: 2px;">Edit</a>
        {%endif%}
        {% if can_delete %}
        <a href="{% url delete_url obj.id %}" style ="border: 1px solid rgb(228, 131, 131) ;color:rgb(230, 109, 109) ; padding: 5px 15px; border-radius: 2px;">Delete</a>
        {%endif%}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="100%">No data found</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div style="border: 1px solid red;">
  <h5>permission</h5>
  <ul>
 {% for perm in user_permissions_list %}
    <li>{{ perm }}</li>
{% endfor %}
</ul>

</div>
{% endblock %}

templates/dash/base_form.html
{% extends "dash/Base_all.html" %}
{% block content %}
<div class="container">
                <div class="">
                    <h2 class="mb-5"> {{ model_name }}</h2>
                </div>

                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        {% for field in form %}
                        <div class="mb-3 form-group {% if field.field.required %}required{% endif %}">
                            <label class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </div>
                        {% endfor %}

                        <div class="d-flex justify-content-between mt-4">
                            <a href="{% url list_url %}" class="btn mb-3" style="background: #bdb9b2; color: white; padding: 10px 5px;">
                                Cancel
                            </a>
                            <button type="submit" class="btn mb-3" style="background: #daa556; color: white; padding: 10px 5px;">
                               Save
                            </button>
                        </div>
                    </form>
                </div>

</div>
{% endblock %}

templates/dash/conf_delete.html
{% extends "dash/Base_all.html" %}
{% block content %}
    <h2>Confirm Delete {{ model_name }} </h2>
    <br>
    <p>Are you sure you want to delete <strong>{{ object }}</strong> ?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'books' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

templates/dash/sidebar.html
{% load custom_filter %}
    <nav id="navmenu" class="navmenu">
      <ul>
        
        <li><a href="{% url 'dash'%}" class="active"><i class="bi bi-house navicon"></i>Home</a></li>
        {% if perms.main.view_category %}
        <li><a href="{% url 'list_cate' %} " class="{% if active == 'Category' %} text-decoration-underline  {% endif %}"><i class="bi bi-list navicon" ></i>Categories</a></li>
        {%endif%}

        {% if perms.main.view_author %}
        <li><a href="{% url 'list_auth' %}" class="{% if active == 'Author' %} text-decoration-underline  {% endif %}"><i class="bi bi-pencil-square navicon"></i> Authors</a></li>
        {%endif%}

        {% if perms.main.view_book %}
        <li><a href="{% url 'book_list' %}" class="{% if active == 'Book' %} text-decoration-underline {% endif %}"><i class="bi bi-book-half navicon"></i> Books</a></li>
        {%endif%}
         {% if  user.is_superuser %}
        <li><a href="{% url 'users' %}"class="{% if active == 'User' %} text-decoration-underline  {% endif %}"><i class="bi bi-people navicon"></i> Users </a></li>
        <li><a href="{% url 'adduser' %}"><i class="bi bi-person-plus navicon"></i> User Add </a></li>
        {%endif%}
        
      </ul>
    </nav>

templates/dash/user_form.html
{%load static%}

{% include 'dashboard/base_add.html'%}
<body >
      

<h3 style="text-align: center;">Add BooK</h3>

<div class="row " style="width: 90%;margin-left: 20px;">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-body-tertiary rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'List_Book' %}">Books</a></li>
            <li class="breadcrumb-item"><a href="#">{{ model_name }} Add </a></li>
          
          </ol>
        </nav>
      </div>
    </div>

<form method="POST" class="form-control" enctype='multipart/form-data' style="padding:20px ; border: 1px solid rgb(230, 223, 223); border-radius: 5px;  margin-left:20px;">
    {% csrf_token %}
    {{form}}
    <button type="submit" style="background:  #daa556; color:white; padding: 15px 50px; 
            border-radius: 2px; margin-left: 10px;"> Add</button>
</form>

</body>